### PR TITLE
include missing vlmcsd.kmd for system identifies

### PR DESCRIPTION
**Pull request by si458**

### CODE REVIEW

**Comment by mikolatero** [comment]
Thanks!

**Comment by si458** [comment]
glad i could help! 
is the any chance of a fresh build on docker hub to include the file?

**Comment by mikolatero** [comment]
Yes, this afternoon I will do the update of the docker image in dockerhub for x86, x86_64, arm and arm64!

**Comment by mikolatero** [comment]
@si458  ready, all images updated.

**Comment by si458** [comment]
> @si458 ready, all images updated.

absolute legend! thank you so much!

**Pull request merged**
